name = volcanic_soil
display_name = Volcanic Soil
description = Super-fertile volcanic ground that degrades to normal soil after repeated harvests.
depends = moreblocks, ore_dust
optional_depends = lava_crucible, farming, x_farming
